language: python
python:
  - "3.6"

script:
  - sphinx-build -W -a -n -q -T -b html . _build
  - rm -rf _build
  - make html
  - touch _build/html/.nojekyll
  - cp CNAME _build/html
  - date -Iseconds >> _build/html/build.info.txt

deploy:
  provider: pages
  local_dir: _build/html
  skip_cleanup: true
  deployment_file: true
  verbose: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
