language: python
python:
  - "3.6"

script:
  - make html
  - cd _build/html
  - touch .nojekyll
  - cd -

deploy:
  provider: pages
  local_dir: _build/html
  skip_cleanup: true
  deployment_file: true
  verbose: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable