language: python
python:
  - "3.6"

before_script:
  - cd docs
  
script:
  - make html

deploy:
  provider: pages
  local_dir: _build
  skip_cleanup: true
  deployment_file: true
  verbose: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable